### ISSUE TITLE
How to know when user logged with a different account in Spotify app?

### ISSUE THREAD

**Issue by zdurlan** [Peter-Schorn/SpotifyAPI#11]
Hello! 

I've encountered a scenario while testing between premium and free accounts: my authorization manager is kept in the keychain with the old account data, even though I have logged in with a different account. 

How can I tell if the user I have in the authorization manager is not the one I am asking to login with?

**Comment by Peter-Schorn** [comment]
After retrieving the authorization information for a user, make a request to the [`SpotifyAPI.currentUserProfile()`][1] endpoint and store the the `uri` property of [`SpotifyUser`][2] along with the authorization information in the keychain. You may also want to store other properties as well, such as `displayName`, so that you can display the name of the user in your app. The `uri` property will be unique to each user.

> How can I tell if the user I have in the authorization manager is not the one I am asking to login with?

If the person using your app has multiple Spotify accounts, then, when you open the authorization URL that prompts them to login, it's entirely up to them which Spotify account to login with before clicking "agree". It's only after Spotify redirects to your app and you retrieve the authorization information that you can determine which account they decided to login with.

[1]: https://peter-schorn.github.io/SpotifyAPI/Classes/SpotifyAPI.html#/s:13SpotifyWebAPI0aC0C11userProfiley7Combine12AnyPublisherVyAA0A4UserVs5Error_pGAA0A14URIConvertible_pF
[2]: https://peter-schorn.github.io/SpotifyAPI/Structs/SpotifyUser.html

**Comment by zdurlan** [comment]
Thakn you so so much! You're amazing and a life saver.

**Comment by Peter-Schorn** [comment]
@zdurlan I just created a branch in my example app that allows you to use multiple accounts. Check it out [here](https://github.com/Peter-Schorn/SpotifyAPIExampleApp/tree/multiple-users).
