### ISSUE TITLE
Setting up SpotifyAPI and Spotify SDK in the same app

### ISSUE THREAD

**Issue by zdurlan** [Peter-Schorn/SpotifyAPI#8]
Hello!

I was wondering if there is a way to use the access token that we got from logging in via Spotify SDK (using session manager) in order to set it to the SpotifyAPI so we can use both of them inside one app, without asking for permissions twice?

In my particular case we need both of them as we need both the track events that we get from the app remote delegate, and the web api functions like search. 

Is there a way to use them both or is it better to just create the search api locally?

**Comment by Peter-Schorn** [comment]
> I was wondering if there is a way to use the access token that we got from logging in via Spotify SDK (using session manager) in order to set it to the SpotifyAPI

Yes, this is possible.

both `AuthorizationCodeFlowManager` ([docs][1]) and `AuthorizationCodeFlowPKCEManager` ([docs][2]) have the following initializers for exactly this purpose:
```swift
public convenience init(
    clientId: String,
    clientSecret: String,
    accessToken: String,
    expirationDate: Date,
    refreshToken: String?,
    scopes: Set<Scope>,
    networkAdaptor: (
        (URLRequest) -> AnyPublisher<(data: Data, response: HTTPURLResponse), Error>
    )? = nil
)
```
You can pass the access token retrieved from the Spotify SDK into these initializers. You'll have to leave `refreshToken` as `nil` because the SDK doesn't seem to provide that (I may be wrong). You should set the expiration date to an hour after the access token was received. Make sure the scopes match what you requested during the authorization process. If you get a "Permissions Missing" error when making a request to an endpoint, then that means you're missing the required scope(s).

The downside of this strategy, however, is that my library cannot automatically refresh the access token after it expires (it expires after an hour), because that requires a refresh token.

**Here's an alternative strategy**:

Authorize your app using the Spotify web API through my library, and include the `appRemoteControl` scope. Then, after the authorization process completes, assign the access token you received to the app remote/session manager.

[1]: https://peter-schorn.github.io/SpotifyAPI/Classes/AuthorizationCodeFlowManager.html#/s:13SpotifyWebAPI28AuthorizationCodeFlowManagerC8clientId0H6Secret11accessToken14expirationDate07refreshL06scopes14networkAdaptorACSS_S2S10Foundation0N0VSSSgShyAA5ScopeOG7Combine12AnyPublisherVyAK4DataV4data_So17NSHTTPURLResponseC8responsets5Error_pGAK10URLRequestVcSgtcfc
[2]: https://peter-schorn.github.io/SpotifyAPI/Classes/AuthorizationCodeFlowPKCEManager.html#/s:13SpotifyWebAPI32AuthorizationCodeFlowPKCEManagerC8clientId0H6Secret11accessToken14expirationDate07refreshL06scopes14networkAdaptorACSS_S2S10Foundation0N0VSSSgShyAA5ScopeOG7Combine12AnyPublisherVyAK4DataV4data_So17NSHTTPURLResponseC8responsets5Error_pGAK10URLRequestVcSgtcfc

**Comment by Peter-Schorn** [comment]
If you need to go through the authorization process multiple times, then you'll need to create a new authorization manager each time (because you cannot mutate that access token) and assign it to `SpotifyAPI.authorizationManager`, which is a mutable property.

**Comment by zdurlan** [comment]
Thanks a lot! This helps a ton.

You are correct in saying that the sdk does not provide a way to refresh the tokens, so I think the other way (logging via your library and assigning the token to the app remote) is the winner here. I just don't know how that will affect the app remote, I would think that it must be reconnected with the new token. I'll have to test it out.

Thanks again!

**Comment by Peter-Schorn** [comment]
Yes, I think the second method is better, based on my limited experience with the SDK. In order to keep the access token for the app remote up to date after my library automatically refreshes it, you need to subscribe to `SpotifyAPI. authorizationManagerDidChange` and reassign the access token from `SpotifyAPI.authorizationManager` to the app remote each time this publisher emits. See this article: [Saving authorization information to persistent storage][1].

You might also want to take a look at the "SpotifySDK" branch of my [example app][2]. It's not very polished and may not represent the best practices, but it may be helpful nonetheless.

[1]: https://github.com/Peter-Schorn/SpotifyAPI/wiki/Saving-authorization-information-to-persistent-storage.
[2]: https://github.com/Peter-Schorn/SpotifyAPIExampleApp/tree/SpotifySDK

**Comment by Peter-Schorn** [comment]
I'm closing this for now. I can reopen it if you have any other questions. I'm always available for help.
